### ISSUE TITLE
Add opt-in ingress for Kibana

### ISSUE THREAD

**Issue by sagikazarmark** [clockworksoul/helm-elasticsearch#11]
Here is my Kibana setup for optional ingress:

`values.yaml`:
``` yaml
ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
    # - kibana.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: kibana-tls
    #   hosts:
    #     - kibana.local
```

`templates/ingress.yaml`:
``` yaml
{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - backend:
              serviceName: {{ $serviceName }}
              servicePort: 80
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
```

With a few changes this could be a great addition to this chart:

- move the `ingress` section under `kibana` in `values.yaml` (and of course change the templates as well)
- suffix names in the template with `-kibana`

Normally I would open a PR, but I'm not sure if I can be responsive these days, so it would take some time to do requested changes, etc, so anyone can pick this if @clockworksoul likes the idea.

If not, I will probably do it later.
