### ISSUE TITLE
Add RBAC

### ISSUE THREAD

**Issue by clockworksoul** [clockworksoul/helm-elasticsearch#25]
Pointed out over at https://github.com/pires/kubernetes-elasticsearch-cluster/issues/140.

Per that issue:
> RBAC is now default and will be much more prominent in kube 1.8. Can you provide the RBAC yaml for this elastic search cluster? #

**Comment by sagikazarmark** [comment]
I would probably provide an opt-in for those who are still on k8s <1.8 and use RBAC.

**Comment by clockworksoul** [comment]
My working version includes the following values: 

```
# If RBAC is enabled, a ClusterRole and ClusterRoleBinding will be created.
rbac:
  enabled: false

  # RBAC API version (currently v1, v1beta1, v1alpha1)
  apiVersion: "v1beta1"
```

Is this the kind of thing you have in mind?
