### ISSUE TITLE
liveness and health probes

### ISSUE THREAD

**Issue by yanns** [clockworksoul/helm-elasticsearch#5]
It'd be great to add liveness and health probes, like:

```
        livenessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /_cluster/health?local=true&timeout=5s
            port: 9200
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
```

See https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html for more info.

I guess it can only be done if http is enabled.
